#!/usr/bin/env bash

RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
NC='\033[0m' # No Color

if ! yarn validate; then
  echo -e "${RED}Validating failed${NC}"
  exit 1
fi

echo -e "${GREEN}Pre-push hook completed successfully.${NC}"
exit 0

