[build]
command = "yarn build"
publish = "public"
  [build.environment]
  # cache Cypress binary in local "node_modules" folder
  # so Netlify caches it
  CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
  # set TERM variable for terminal output
  TERM = "xterm"


[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    # run E2E tests against locally built site
    # before deploying it
    enable = true
