name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvm

    - name: Set up Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

    - name: Install Yarn
      run: npm install -g yarn
      if: ${{ env.ACT }}

    - name: Cache dependencies
      uses: actions/cache@v2
      if: ${{ !env.ACT }}
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      run: yarn

    - name: Run linters
      run: yarn lint

    - name: Run type-check
      run: yarn type-check

    - name: Run tests and generate coverage report
      run: yarn test --coverage --ci ----passWithNoTests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
